# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: terraform-yaml-config
  description: Terraform module to convert local and remote YAML configuration templates into Terraform lists and maps
  homepage: https://cloudposse.com/accelerate
  topics: configuration, config, configuration-management, configuration-files, yaml, yaml-configuration, yaml-files, terraform, terraform-module, template, templates, template-engine, templating



