escalations:
  - name: example-team-escalation-to-${infrastructure_team_name}
    description: "Escalate to '${infrastructure_team_name}' team if 'example-team' does not acknowledge in 10 minutes"
    owner_team_name: example-team
    rule:
      condition: if-not-acked
      notify_type: all
      delay: 10
      recipients:
        - type: team
          team_name: ${infrastructure_team_name}
    repeat:
      wait_interval: 10
      count: 2
      reset_recipient_states: false
      close_alert_after_all: false
