import:
  - imports-level-4

vars:
  namespace: eg

terraform:
  vars:
    var_1: 1
    var_3: 3

helmfile:
  vars: {}

components:
  terraform:
    vpc:
      backend:
        s3:
          workspace_key_prefix: "vpc"
    eks:
      backend:
        s3:
          workspace_key_prefix: "eks"
      vars:
        cluster_kubernetes_version: "1.18"
